# Generated by Django 5.0.4 on 2024-04-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0002_featurerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='status',
            field=models.CharField(choices=[('New', 'Новая'), ('In_progress', 'В работе'), ('Completed', 'Завершена')], default='New', max_length=50),
        ),
        migrations.AddField(
            model_name='featurerequest',
            name='status',
            field=models.CharField(choices=[('Consideration', 'Рассмотрение'), ('Accepted', 'Принято'), ('Rejected', 'Отклонено')], default='Consideration', max_length=50),
        ),
    ]
